import { ClientProfile, ContentItem, ChecklistTask, TargetClient, ProspectingChannel } from './types';

export const ASSETS = {
  logo: "https://lh3.googleusercontent.com/aida/AEtjO1UK0sYY3NfqOYkRETKNeBkeshxVIlp6Ph-xAw0WpOuLPrmdg_kgblRtxTqgcigrXZTWbw62KG8hjNXcOwbi09bWTRhT3B1AHY5JkGtFoOxk357aKbiP8Pdt9xUKDJwjlywc194xBfrb_knJ5hETHocfCMFQkZfvz3lnrHBc0buvhfoJS7hRJbj6diE5U7Bwt_acwUOIDx7htIltVLRdq_8pgQT2owm_4hcGCmy8XB6abgNOenjNSGUzU-sH",
  userAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuD0FAAgEuOgs8O0fE2UIda09B47gGudEYDWQYQV2x3NHmhsv9cfJmnH7aCtzXMU9N0xbKZySMTNUs8ZWvOWrKXcYfU8cd7y60kDi6vyKGZvAvB8N-J1Jc53UDzHG1sgKpq6TgUR6SQNZwV68x-B9ikW21VyNXZyV6dLJ_281wIqK5P2nZYtmxg8PctV1qWraca-j-06VTyohAc2rcL8ndZuIwJxtQYLuLx0qsuLCeDqDk1noWcIVbmR_g",
  auraStudioAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCtzYimQs_RX8kBv7lojOZxQ0ZQMiPjz8_CtUyLTaPTq_mlnJftSDLe7ahnF2AavrL0mBdIGIgLSWszvc7aSCJKFYAEfhAUfW6e-y0vIdz-de5JWiZSQNNE3xPOZAcqq4n69rb4oIcUMauWSNDUnGg_Vhyq8ICvFcbwqSUdtyVwBfZOQ5ql2hHMraL7iup6bEZvBTPy7YdUlMZoUUGL2x33yFPga3RI7ioW9V947UdHBlvDZHVb9MbM_w",
  topPerformingReelThumb: "https://lh3.googleusercontent.com/aida-public/AB6AXuDRvghYEX-5ofSZhs-B1ETMlQ3nyBjMwhVbRb3DOQVhTW1877acq0UPXkqm4Zqc85PS005Vbh53l-XOT9HJ3mB6WP1gr9pVwsMMsqbt041MJoYlg_9WlZN2y6l8EycTj1OKcLyVIQ3IJv9yTb6hEV95zZfy6A8aPY9IKVomQoCqzQMBOfwLBdx6CADShQe_vXoSWe7EG21RsCeIp01bXaq6q2TqUF5hDMqZPIFaGS6MEqgi9G7YK2Lzng",
  matrixReelPostA: "https://lh3.googleusercontent.com/aida-public/AB6AXuA3yQVXNx76u_IPydYxSFAXbapMx69BS_BY95T1wk_xxPR-PxYe3ZBlVCrKDfeCC4C-TWc9eCi3_7YlOaw4GAx0Xb6-fbHnSksJXeRVYLFu-nmcE0hQOi51jUGPRf2bs9vZPdVmL9zrK792ie71-z4_rtpjq5tFRa1_3v6WC5sg0JEmTHSqEFlvug6gIL_PPviJV-uS1B_61jtVbf-4F3FL2oZKce6EhExVHtQ7eiCfzsGwWqaJMHi_bg",
  matrixCarouselPostB: "https://lh3.googleusercontent.com/aida-public/AB6AXuBNsgbeC6lvPoa2UXbk_U8QS4eOvUSstL-CuS2mUlSGvvEIJ9MXJgaOu2NMyvEC29zKoYooQ0H-6kq2MjivGpPYDvpuJ0_9NzHH7Bx-zxv5MQ2NdmHTZVTwOJ6Ytap5atdEnUj8zzMesJzWM72uEow6VsZJc8kUXdk7XuwJ6bwGLB6gSmG5aooXGC80wTRI5wFooa6F1R--fezwuJ8OIRM1GdpggYRwNycFfOelD5IMC6qVITs9NJI9SQ",
  matrixQuotePostC: "https://lh3.googleusercontent.com/aida-public/AB6AXuC8dcPV5CAozJDch9xXXzneQGj8pI2s0D-0HTJC4KuqoylnVCv96bvzkRz80GBPM7WRq4PmK3AjhSjcQCwVYafrCMANCIn4A-cgW2XutK68HGzMgkg_VcPtqQPfhoeqF3Ok83neAKqUfWDUW3nBNoSrZ6--m3M1ibID7MU4ioq1_bld6zjP0auWrK2nL5sNOxxmqRMaXFihOGRKajEX1AT9_hVd9_M-xTLr7gJGZC8gt3wzJo357C5FGg",
  matrixVlogPostD: "https://lh3.googleusercontent.com/aida-public/AB6AXuBNMcsIisiE6yb_SHuBJj2ojwRVn8pBx4CwkyDyrKLWj9NHP7ZRVAaZ_qlMLkAadIWIv2ArVp0Cad_oK_gY1JMa9-PBoilIejRvwQRszxExafdxZsEaWfQ2YNZtj8CC0awCP-GJClP_gMplRe8U2wYj-ouZ5c2yd3GWIZNVcQ37yx6I5A3VQmywOv71EXTe4J4QwJcOU3gwjsCJZDa5l9-W_9N6XR7cgkAVrltTc-jwTYInivB9McHUSw",
  obs1Image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCr9Ba3I1wHbaSa-ms_t1WkoeuiRsRp0UFv027-PfQ_mWB4mgm1DXL33p1uNYJIcJKBmNUGnuP8jPBq4VAL57k5ZZJ95EyywfOmSJ0r6EU0w5V0fI9vA-HRsd7gdO8nxeQaBTMJnrW9jIMU2XOlCArb9kUCdy2zf1u9aKdx-iTZ83qL1Sv680ZUieG6ftk4ulQ4lFBQeiSKipgiLFVUju8ppNKc8PjK_syMCPu3f6CWHXKC51Tjml5M7Q",
  obs2Image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAFrmMIRsrvKAcl0a9VMRcWI5qYkY-5Ftk208goLXI5Irl7zT_qjHnWzJVs5G5aEf3c_EbxVSo1GNO3FOzXWIor_sYvaiSFVySy4mNaxWqA6gRmYbEd-I4yvOZhP0hE3RDnmblfbVkXMGPrAxnZtSjuTR_-VxOsUR2vaFMtdXt8IzzGekL9PVXxDAnlxJXoy2ImXHt-xzcOj8O1EsEwGAzDGNbfOCIEi7-lv7xPeGMmlbWUvoEQH9morQ",
  elenaVancePortrait: "https://lh3.googleusercontent.com/aida-public/AB6AXuAGLX3GtMcdaTriJt7tx8bL9KB4U5PUmqY9OJjmegYivrnh_MQP0yoJOb4WI3UZTMOtZsZ7QzmqOlnikImyq1ZwUJTDZ733a10sSR147DvbN9TNJg7H0_Z-XxWCJBnb8loix-DdFO0IUkQFTkX4bw-bJe0tLPEl3hq1WAT8n-wJHVRGHiXYSQZGuMgK2d2-iMF5BBTVNkB6BCjitZE7PD0AgU87PEPO1EzTxtOl-dzfM5oZ4UsUQeK1Lw",
  elenaVancePortraitHighRes: "https://lh3.googleusercontent.com/aida-public/AB6AXuDYygzDro2cEZuGs2O1ZRUXseWC3icf1ykdfbtivv5b4vIMwUucvz8rkcMfbPvyXGCDwHUj-Y-tzCyfyU5OdfXGvlo4USFP-3V01iHaIw2aMfyGjDB36IJB6RpzEtuK7mqlr7E_j924z6PEBQyeGtNRyeepuwqqBUP0uFMRKF2eRRJpOuf9Jz7AnLqK13kA_xqkS2EB-JjVBvKO7IusKyAtVp2O6I1OTb3G_FJ1IYZMTwk_T4HzflZVJw",
  sampleDeckShowcase: "https://lh3.googleusercontent.com/aida-public/AB6AXuC8IgoNH7ru1bYJ_qLlMvTQ1muViLeBa_WvI14qziFdoC1_4rGR7ptLmFRNR13sc14KR-8AskQXi25kH7RBGZ0sof9GQiyobVXAqD40V1qRoa6RC9iIzjYSwtd2OdQG7lBn4y6hHXH4NRc0EGnPSrFyIKBCQEh2jbfKgCNZEMw0Qta0Cl-VoShcbjNnFKQaL3ibWfy3WhIPzHyAjAsmQFrWGW08uGTzlJi6JzyCztl2y63D1NNjarizNQ",
  husnaAnjumPortrait: "https://lh3.googleusercontent.com/aida-public/AB6AXuAymLjG_qUiKp1u20fpnYJjaIlHUjoPC4pzR41hi4xZDK0vGVHGIkLjEb7emWXmk9A0l9gtdY29F6zw4gAZamcwR9JF-vlk6o5msFVY1XixiuDGORi-Xk2NXMEKECI5dNlAW-NYJOwh65e31LA_Tr9sbvmpHE_-S7BHp-31bEjlx0XYjDLwH8eCScESPE5hj0NJ38KZZ_IMBDqnULly8pCabASo0W9uUlAC-zxbzLPRVS1TYR7IW6pj_Q",
  testimonialMarcus: "https://lh3.googleusercontent.com/aida-public/AB6AXuCL8sdebbl5FWHpkz1L3bsOSyqFc8mB20kTz552wI1z8twjm37qGtR11Hktqr_7ccIeXrlZR-XF4-BFCJErmxCUgDyKD_RK61cim4SNMKf2AdcawJJQssJir56V3qC7WUbmzbqB6gtM_B1BD-sbs0TtvlHycuu4pi4LC4RIOkURoojIDC7Ic6VC1d31usNYyMIrOEAUc_cmqUm2LgjrGolf5Zn3nkDThndn4xJ84wO-hexGNYpnhzuOXg",
};

export const DEFAULT_CLIENT: ClientProfile = {
  id: 'aura-skin-studio',
  name: 'Aura Skin Studio',
  tier: 'Instagram & YouTube Creator Tier',
  fee: '$150/mo',
  auditPeriod: 'October 2024 Performance Audit',
  avatarUrl: ASSETS.auraStudioAvatar,
  healthScore: 88,
  healthScoreMom: '+6.4%',
  healthSummary: 'Exceptional virality conversion on Reels and high retention from YouTube Shorts subscribers.',
  totalAudience: '48.2K',
  totalAudienceChange: '+2,340',
  totalAudienceGrowthPercent: '+5.1%',
  monthlyReach: '312.4K',
  monthlyReachChange: '+18.2%',
  reelsShare: 74,
  feedShare: 26,
  engagementRate: '4.8%',
  engagementBenchmark: '2.1%',
  engagementMom: '+1.4%',
};

export const SAMPLE_CLIENTS: ClientProfile[] = [
  DEFAULT_CLIENT,
  {
    id: 'luminance-glow',
    name: 'Luminance Wellness',
    tier: 'E-Commerce Brand Retainer',
    fee: '$199/mo',
    auditPeriod: 'October 2024 Performance Audit',
    avatarUrl: ASSETS.testimonialMarcus,
    healthScore: 82,
    healthScoreMom: '+4.1%',
    healthSummary: 'Consistent educational carousel saves with high conversion to Shopify checkout.',
    totalAudience: '72.6K',
    totalAudienceChange: '+3,820',
    totalAudienceGrowthPercent: '+5.6%',
    monthlyReach: '445.0K',
    monthlyReachChange: '+22.4%',
    reelsShare: 68,
    feedShare: 32,
    engagementRate: '4.2%',
    engagementBenchmark: '2.1%',
    engagementMom: '+0.8%',
  },
  {
    id: 'kinetic-agency',
    name: 'Kinetic Tech Media',
    tier: 'Executive Growth Tier',
    fee: '$350/mo',
    auditPeriod: 'Q3 2024 Audit Cycle',
    avatarUrl: ASSETS.userAvatar,
    healthScore: 94,
    healthScoreMom: '+8.9%',
    healthSummary: 'Dominant YouTube Shorts presence with accelerating B2B inbound inquiries.',
    totalAudience: '118.4K',
    totalAudienceChange: '+8,150',
    totalAudienceGrowthPercent: '+7.4%',
    monthlyReach: '890.2K',
    monthlyReachChange: '+34.1%',
    reelsShare: 81,
    feedShare: 19,
    engagementRate: '5.9%',
    engagementBenchmark: '2.1%',
    engagementMom: '+2.1%',
  },
];

export const MATRIX_ITEMS: ContentItem[] = [
  {
    id: 'post-a',
    letter: 'A',
    category: 'winners',
    format: 'Short Reel',
    typeBadge: 'SHORT REEL',
    publishedDate: 'Published May 12',
    duration: '0:24',
    title: '3 Morning Skin Mistakes You Are Making',
    subtitle: 'Barrier repair & active ingredient timing breakdown',
    reach: '84.5K',
    saves: '1,420',
    metric3Label: 'Engage',
    metric3Value: '8.6%',
    isPositiveMetric3: true,
    takeawayTitle: 'Winning Factor',
    takeawayText: 'Strong hook within 1.8s + educational save-ability drove 2.4x standard algorithm recirculation.',
    thumbnailUrl: ASSETS.matrixReelPostA,
  },
  {
    id: 'post-b',
    letter: 'B',
    category: 'winners',
    format: 'Carousel',
    typeBadge: 'CAROUSEL',
    publishedDate: 'Published May 18',
    slides: '6 slides',
    title: 'Ceramide vs Hyaluronic Guide',
    subtitle: 'Swipeable clinical efficacy decision tree',
    reach: '42.1K',
    saves: '2,105',
    metric3Label: 'Shares',
    metric3Value: '412',
    isPositiveMetric3: true,
    takeawayTitle: 'Utility Insight',
    takeawayText: 'Exceptionally high 5.0% save-to-reach ratio. Acts as evergreen reference collateral for consumer re-visits.',
    thumbnailUrl: ASSETS.matrixCarouselPostB,
  },
  {
    id: 'post-c',
    letter: 'C',
    category: 'needs-pivot',
    format: 'Quote Card',
    typeBadge: 'QUOTE CARD',
    publishedDate: 'Published May 22',
    reachDelta: '-74% reach',
    title: 'Monday Motivation Quote',
    subtitle: 'Inspirational morning copy overlay',
    reach: '3.2K',
    saves: '12',
    metric3Label: 'Engage',
    metric3Value: '0.8%',
    isPositiveMetric3: false,
    takeawayTitle: 'Diagnosis & Recommendation',
    takeawayText: 'Low organic save value. Feed algorithms deprioritizing generic text graphics. Pivot budget immediately to motion carousels.',
    thumbnailUrl: ASSETS.matrixQuotePostC,
  },
  {
    id: 'post-d',
    letter: 'D',
    category: 'needs-pivot',
    format: 'Vlog Reel',
    typeBadge: 'VLOG REEL',
    publishedDate: 'Published May 25',
    duration: '0:45',
    reachDelta: '68% drop-off',
    title: 'Studio Restock Day',
    subtitle: 'Warehouse unboxing & inventory prep',
    reach: '6.8K',
    saves: '34',
    metric3Label: 'Engage',
    metric3Value: '1.1%',
    isPositiveMetric3: false,
    retentionPercent: 32,
    takeawayTitle: 'Drop-Off Diagnosis',
    takeawayText: '68% bounce rate within first 3 seconds due to slow visual pacing and lack of on-screen text hook. Re-edit with rapid cut transitions.',
    thumbnailUrl: ASSETS.matrixVlogPostD,
  },
];

export const INITIAL_CHECKLIST: ChecklistTask[] = [
  {
    id: 1,
    title: 'Batch Script 6 Myth-Busting Hooks',
    description: 'Use the PAS (Problem-Agitate-Solve) template provided in appendix deck.',
    priority: 'High',
    completed: false,
  },
  {
    id: 2,
    title: 'Update Sprout Social Scheduling Slots',
    description: 'Shift prime distribution slots across Instagram and TikTok to 7:15 PM EST.',
    priority: 'High',
    completed: false,
  },
  {
    id: 3,
    title: 'Archive Static Quote Post Templates',
    description: 'Clean the Figma content repository to prevent accidental designer recycling.',
    priority: 'Medium',
    completed: false,
  },
  {
    id: 4,
    title: 'Review First 3 Q&A Native Drafts',
    description: 'Submit raw footage to PulseMetrics workspace for tone & hook signoff.',
    priority: 'Medium',
    completed: false,
  },
];

export const TARGET_CLIENT_PROFILES: TargetClient[] = [
  {
    id: 'ecom',
    icon: 'storefront',
    title: 'E-Commerce & IG Brands',
    badge: 'Very High',
    badgeType: 'tertiary',
    description: 'Struggling to calculate organic conversion lift',
    rate: '$149/mo',
  },
  {
    id: 'creators',
    icon: 'smart_display',
    title: 'Creators & YouTubers',
    badge: 'High',
    badgeType: 'primary',
    description: 'Posting short-form video blindly without retention data',
    rate: '$199/mo',
  },
  {
    id: 'coaches',
    icon: 'psychology',
    title: 'Coaches & Consultants',
    badge: 'Immediate',
    badgeType: 'tertiary',
    description: 'Need authority-building proof for high-ticket funnels',
    rate: '$199/mo',
  },
  {
    id: 'agencies',
    icon: 'corporate_fare',
    title: 'Boutique Agencies',
    badge: 'Bulk Retainer',
    badgeType: 'secondary',
    description: 'White-label reports for 5-10 of their existing clients',
    rate: '$500+/mo',
  },
];

export const PROSPECTING_CHANNELS: ProspectingChannel[] = [
  {
    id: 'ch-ig',
    icon: 'photo_camera',
    name: 'Instagram DM Search',
    tag: '10k-50k Followers',
    tagColor: 'text-[#4edea3]',
    description: 'Search niche keywords (e.g. "sustainable apparel", "mindset mentor"). Identify accounts with 10k+ followers but comments below 15 per post. They feel the reach drop and want answers.',
  },
  {
    id: 'ch-yt',
    icon: 'play_circle',
    name: 'YouTube Shorts Underperformers',
    tag: '<1k Views Plateau',
    tagColor: 'text-[#ffb4ab]',
    description: 'Channels with strong subscribers (5k-25k) whose Shorts stall under 1,000 views. They are desperately testing formats and will pay for a breakdown of their drop-off timestamps.',
  },
  {
    id: 'ch-li',
    icon: 'badge',
    name: 'LinkedIn Creator Mode Founders',
    tag: 'B2B Founders',
    tagColor: 'text-[#c0c1ff]',
    description: 'Filter by "Founder" + Creator Mode active. They post 3x/week but lack systematic metrics to know if their personal branding yields inbound pipeline.',
  },
  {
    id: 'ch-clutch',
    icon: 'hub',
    name: 'Clutch & Agency Directories',
    tag: 'Wholesale Scale',
    tagColor: 'text-[#4edea3]',
    description: 'Email boutique design/web agencies offering back-office social intelligence reports for their retainer clients without them hiring an in-house analyst.',
  },
];

export const PITCH_SCRIPT = `Hey [Name], caught your recent post on [Topic] — the point on [Specific Quote] was super sharp.

Noticed your reach numbers have been fluctuating slightly with the latest algorithm adjustment. I run monthly intelligence audits for [Niche] brands, breaking down exact winning hooks vs wasted spend so you don't have to decipher graphs.

I put together a 3-point micro teardown of your top performer this week. Mind if I drop a 60-second preview here? No pitch, just free ammo for your team!`;
